name: Prune Branches

on:
  push:
    paths:
      - '.github/workflows/prune_branches.yml'
  schedule:
    - cron: '0 12 * * *'

jobs:
  remove:
    name: Remove Old Branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crossbow
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Delete Branches
        env:
          DRY_RUN: 0
        run: ./delete_old_branches.sh "380 days ago"
