name: Report

on:
  workflow_call:
    inputs:
      report_type:
        required: true
        type: string
    secrets:
      CROSSBOW_GITHUB_TOKEN:
        required: true
      CROSSBOW_SMTP_USER:
        required: true
      CROSSBOW_SMTP_PASSWORD:
        required: true
      CROSSBOW_ZULIP_WEBHOOK:
        required: true
      CROSSBOW_SLACK_WEBHOOK:
        required: true

jobs:

  nightly-report:
    name: Send and build nightly ${{ inputs.report_type }} report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Arrow
        shell: bash
        run: git clone https://github.com/apache/arrow
      - name: Checkout Crossbow
        uses: actions/checkout@v3
        with:
          path: crossbow
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Archery
        shell: bash
        run: pip install -e arrow/dev/archery[crossbow]
      - name: Send Report
        shell: bash
        env:
          CROSSBOW_GITHUB_TOKEN: ${{ secrets.CROSSBOW_GITHUB_TOKEN }}
        run: |
          job_prefix=nightly-${{ inputs.report_type }}-$(date -I)
          job_id=$(archery crossbow latest-prefix ${job_prefix})
          echo "Sending report for job ${job_id}..."
          archery crossbow report \
            --send \
            --sender-name Crossbow \
            --sender-email 'crossbow@ursalabs.org' \
            --recipient-email 'builds@arrow.apache.org' \
            --smtp-user ${{ secrets.CROSSBOW_SMTP_USER }} \
            --smtp-password ${{ secrets.CROSSBOW_SMTP_PASSWORD }} \
            ${job_id}
          echo "Sending Slack report for job ${job_id}..."
          archery crossbow report-chat \
            --send \
            --no-fetch \
            --webhook ${{ secrets.CROSSBOW_SLACK_WEBHOOK }} \
            --extra-message-failure "@labs_team there has been some failures :cry:" \
            --extra-message-success "Well done! There are no failures! :tada:" \
            ${job_id}
          echo "Sending Zulip report for job ${job_id}..."
          archery crossbow report-chat \
            --send \
            --no-fetch \
            --webhook ${{ secrets.CROSSBOW_ZULIP_WEBHOOK }} \
            ${job_id}
          echo "Generating ${job_id} CSV ..."
          cd crossbow/csv_reports
          archery crossbow report-csv \
            --save \
            --no-fetch \
            ${job_id}
      - name: Commit CSV report
        shell: bash
        run: |
          job_prefix=nightly-${{ inputs.report_type }}-$(date -I)
          cd crossbow
          echo "Adding file to repo"
          git add csv_reports/*.csv
          echo "Commit CSV"
          git -c user.name="github-actions[bot]" -c user.email="github-actions[bot]@users.noreply.github.com" \
            commit -m "Auto commit ${job_prefix} CSV"
          echo "Pushing to repo"
          git push origin
